
[functions.increment-view-count]
enabled = true
verify_jwt = true
import_map = "./functions/increment-view-count/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/increment-view-count/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/increment-view-count/*.html" ]

[functions.record-and-get-interaction-stats]
enabled = true
verify_jwt = true
import_map = "./functions/record-and-get-interaction-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/record-and-get-interaction-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/record-and-get-interaction-stats/*.html" ]
